// Mocks generated by Mockito 5.0.16 from annotations
// in bloc_minimal/test/bloc/sample_bloc_test.dart.
// Do not manually edit this file.

import 'package:bloc_minimal/dependency.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Dependency].
///
/// See the documentation for Mockito's code generation for more information.
class MockDependency extends _i1.Mock implements _i2.Dependency {
  @override
  void test() => super.noSuchMethod(Invocation.method(#test, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
